name: Building bootable container and ISO image

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  CONTAINER_IMAGE_REGISTRY: ghcr.io
  CONTAINER_IMAGE_NAMESPACE: ${{ github.repository_owner }}
  CONTAINER_IMAGE_TAG: latest
  ISO_IMAGE_STORAGE_URL: https://${{ secrets.CLOUDLFARE_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

jobs:
  build-container:
    name: Building and pushing bootable container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checking out the repository
        id: checkout-repository
        uses: actions/checkout@v6

      - name: Freeing some disk space
        id: free-disk-space
        run: rm -rf /opt/hostedtoolcache

      - name: Building bootable container image with Buildah
        id: build-container
        run: |
          buildah build \
            -t "${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_TAG }}" \
            .

      - name: Pushing bootable container image to GitHub Container Registry
        id: push-container
        run: |
          buildah push \
            --creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            "${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_TAG }}"

  build-iso:
    name: Building and publishing ISO image
    runs-on: ubuntu-latest
    needs: build-container
    permissions:
      contents: read
    steps:
      - name: Checking out the repository
        id: checkout-repository
        uses: actions/checkout@v6

      - name: Freeing some disk space
        id: free-disk-space
        run: rm -rf /opt/hostedtoolcache

      - name: Building ISO image with bootc-image-builder
        id: build-iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          image: "${{ env.CONTAINER_IMAGE_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_TAG }}"
          config-file: ./config/iso.toml
          types: |
            anaconda-iso
          rootfs: ext4
          additional-args: --use-librepo=True

      - name: Renaming ISO image
        id: rename-iso
        run: |
          sudo mv \
            ${{ steps.build-iso.outputs.output-directory }}/**/*.iso \
            ${{ steps.build-iso.outputs.output-directory }}/${{ env.IMAGE_NAME }}.iso

      - name: Uploading ISO image to Cloudflare R2
        id: upload-iso
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDLFARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDLFARE_R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ env.ISO_IMAGE_STORAGE_URL }}
        run: |
          aws s3 cp \
            ${{ steps.build-iso.outputs.output-directory }}/${{ env.IMAGE_NAME }}.iso \
            s3://${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}.iso
